### ISSUE TITLE
Using setInterval to make a drum pattern, eventually loses beat

### ISSUE THREAD

**Issue by PCMACHero** [dinchak/node-easymidi#10]
Is there a more precise way to keep on time, other than using one setTimeout with a bunch of seIntervals inside? As is, I am making a seperate setInterval for each element (bass, snare, hihat) and just giving each their own timing, but it loses beat.

**Comment by dinchak** [comment]
i would recommend using a virtual midi port to route midi clock from your DAW into your node application and using the midi clock signal as a trigger

**Comment by PCMACHero** [comment]
Thanks for the quick reply. I wound up using input on clock, and triggering things inside that, and it is one time. The only problem now is that I dont know what clock it is using so I dont know how to change the speed.

**Comment by dinchak** [comment]
are you using some kind of DAW program like ableton or FL studio? if so, the following setup is how i generally do this kind of stuff:

* 1 virtual midi port for clock signal.  sync out in the DAW, listen to clock events in node.
* 1 virtual midi port for midi back into the DAW.  midi out from node, listen for midi notes in DAW.

then when you hit play on the DAW you will see the midi clock triggers, 48 per beat.  changing the BPM In your DAW should change the speed of the clock and your midi coming from node should be in sync with everything.

**Comment by PCMACHero** [comment]
That sounds great. I am using Logic Pro X. I already have a virtual out that works (triggers notes in DAW), but for some reason my virtual in is never triggering on "clock".

**Comment by PCMACHero** [comment]
I just found the issue. For some reason creating a virtual in doesnt work, but if I use one of my real midi-ins, it works and triggers on input.on(clock). Dont know why virtual_Input.on(clock) never triggers
.

**Comment by dinchak** [comment]
glad you got it working! weird though, i'm not sure, it's generally worked for me in the past.  it uses node-midi under the hood for the actual virtual midi ports so it could be an issue there.

**Comment by PCMACHero** [comment]
Now I dont know how to "get" the bpm. The speed does indeed increase or decrease as I increase or decrease on my midi device, but there is no way to tell when a loop has ended/started. I guess I can have a counter that adds one on each "clock", and each time it reaches 48 is a beat. Thanks!

**Comment by dinchak** [comment]
yep, you've got it, count 48 for a beat.  i think you'll want to set the counter to 0 when you get a 'reset' message as well, this message should come through when you push stop twice.

**Comment by dinchak** [comment]
closing!
