### ISSUE TITLE
New to MIDI, attempting to use my Launchpad Pro, and it can't find it

### ISSUE THREAD

**Issue by 0x57e11a** [dinchak/node-easymidi#12]
Launchpad is on, plugged into my laptop, I ran the Node.js code, and I get this:
```fix
Error: No MIDI output found with name: Launchpad Pro
```

My code: 
```js
let midi = require('easymidi');
let input = new midi.Input('Launchpad Pro');
let output = new midi.Output('Launchpad Pro');

input.on('noteon',msg => {
  console.log(msg);
});
```

**Comment by dinchak** [comment]
Hello! My guess is it's not called "Launchpad Pro", even though that name would make sense.  It's probably something slightly different.  If you look in the `examples` folder you'll see a `list_ports.js`.  Try running this to see what the exact name of the MIDI port is and see if that helps.

**Comment by 0x57e11a** [comment]
Ok! Thanks a bunch!

**Comment by 0x57e11a** [comment]
It was `Launchpad Pro 0`, thanks a lot @dinchak :)
