### ISSUE TITLE
Can't read any other streams than 'noteon'

### ISSUE THREAD

**Issue by SchnoppDog** [dinchak/node-easymidi#14]
Hi,
so I've been working with your repo to manage a project. Now I wanted to expend it a little further by reading something like the "ply aftertouch". I used your example for that but changed the midi-input-device to my own piano. When I press a key with polyphonic aftertouch I don't get any data on my console as output. I've tried that with the 'noteoff' too and there I don't receive any data too. I only receive 'noteon' messages. Do you have an idea why?

**Comment by dinchak** [comment]
Hello! Sorry to hear you're having trouble.  I just tested with an LPK25 keyboard, which doesn't have aftertouch unfortunately, but I was able to see both noteon and noteoff messages.  Here's how I tested it:

First, I got the name of the midi input using the `list_inputs.js` example program

```
tom:~/src/node-easymidi/examples$ node list_ports.js
MIDI inputs:
[ 'LPK25' ]
MIDI outputs:
[ 'LPK25' ]
```

Next I modified the `input.js` example program to use the LPK25 device:

```
var input = new easymidi.Input('LPK25');
```

Note that I removed the `true` argument above so I'm not creating a virtual MIDI port, I'm opening an existing MIDI port.

Finally I ran `input.js` and pushed some keys:

```
tom:~/src/node-easymidi/examples$ node input.js
noteon 53 47 12
noteoff 53 127 12
noteon 57 1 12
noteon 55 1 12
noteoff 55 127 12
noteoff 57 127 12
```

Hopefully this example clears things up for you, if not feel free to post example code and I can try to take a closer look!

**Comment by SchnoppDog** [comment]
Hi there, sorry for taking so long to reply. Those are my inputs:
```
pi@raspberrypi:~/Dokumente/piano-project/lib/test $ node getUsbDevices.js 
[ 'Midi Through:Midi Through Port-0 14:0',
  'Digital Piano:Digital Piano MIDI 1 20:0' ]
```
Notice that the first Device might be some virtual device initialized by raspberry pi. The second device is my piano.
Now if I change the device in `input.js` to my piano run it and push some keys this is what happens for me:
```
pi@raspberrypi:~/Dokumente/piano-project/lib/test $ node input.js 
noteon 33 45 0
noteon 33 0 0          //<--- this should normally be a noteoff
noteon 33 54 0
noteon 33 0 0          //<--- this also should be a noteoff
```

There is also one message I don't understand yet. Could you explain me what "cc" stands for? I noticed it while pressing down my piano pedal it jumps to this value:
``` 
cc 64 0 0
cc 64 127 0
```
But anything else like poly aftertouch, channel aftertouch etc. isn't displayed. Only the noteon-function and the cc-function.

**Comment by dinchak** [comment]
Sorry, I'm not sure why you aren't seeing noteoff messages, it could be related to the device.  I have not seen this behavior on any of my devices.

The cc messages denote MIDI "control change" messages.  Mod wheels, pitch bend wheels, knobs, faders, etc. generally send these type of messages.
