### ISSUE TITLE
Can't send mtc messages.

### ISSUE THREAD

**Issue by Alpakat** [dinchak/node-easymidi#15]
Hello,
I'm trying to send mtc messages, but I don't get it working. I can send messages without errors and the receiving program can see something, but right now I'm just guessing what values correspond to which function (second, minutes, hours, etc.). For example, I found out, if I set the "type" to 1 and "value" to something between 10 and 15 it decreases the seconds by 1. I found [this](https://en.wikipedia.org/wiki/MIDI_timecode) Wikipedia article which would explain the "type", but I can't make any sense of the "value".

**Comment by dinchak** [comment]
Closing this but acknowledging that more testing/work needs to be done with MTC.  Contributions greatly appreciated as I don't have any use cases to test.
