### ISSUE TITLE
Virtual inputs & outputs switched?

### ISSUE THREAD

**Issue by rveitch** [dinchak/node-easymidi#23]
While I was testing some very boilerplate code from the readme I noticed that after initializing virtual inputs and outputs the virtual devices appear in the opposite device list as expected.  Is this incorrect, or do I have my concept of the ins and outs crossed? 

![image](https://user-images.githubusercontent.com/12876929/97929586-1f41b380-1d2f-11eb-9abc-3593f8d741bd.png)

Example code to reproduce:

```js
const easymidi = require('easymidi');

const virtualInput = new easymidi.Input('Virtual input name', true);
const virtualOutput = new easymidi.Output('Virtual output name', true);

const inputs = easymidi.getInputs();
const outputs = easymidi.getOutputs();

console.log('inputs:', inputs);
console.log('outputs:', outputs);
```

**Comment by dinchak** [comment]
Thanks for the question.  It is a little confusing, when you create an Output in your software, the system creates a corresponding virtual MIDI Input to receive your output data, as ultimately you want to send output and output arrives on a MIDI Input.
