### ISSUE TITLE
ts declaration of Output.send() is missing sysex as an input option

### ISSUE THREAD

**Issue by Pckool** [dinchak/node-easymidi#24]
## Problem
As of now, the output function `.send()` does not accept "sysex" as an input when using typescriot even though it is valid.
## Workaround:
Use `// @ts-ignore` above the line

## Expected
"sysex" to be available as a first argument into the `Output.send()` function.

## ex.
![image](https://user-images.githubusercontent.com/10131267/110854389-e6888c80-8282-11eb-84f1-91e28481ede6.png)

**Comment by Pckool** [comment]
pushed the fix

**Comment by dinchak** [comment]
much appreciated! published to npm as v2.0.2
