### ISSUE TITLE
can't change midi input device after electron or node js start

### ISSUE THREAD

**Issue by elmcapp** [dinchak/node-easymidi#26]
If you select a midi device input you can read the midi messages coming in however if you change the midi input device you have to restart the full program before you can read message from the new port

**Comment by dinchak** [comment]
Sorry, I'm confused by your issue.  Can you provide more info on what you're trying to do?

**Comment by elmcapp** [comment]
I am using easyMidi with Electron.  I have a select box that show all attached midi devices. Then I am using "selectedDevice" which the selected midi device. The problem that I have is that if I select midi device 1 when the program start I will read midi from midi device 1. Lets say that I need to change to midi device 2. Easy midi still reads midi message from device 1 into I stop and restart the program. 

Its like I can't clear the input listener or input event listener.

**Comment by dinchak** [comment]
Have you tried `.close()`ing midi device 1 and then creating a new device for midi device 2?

**Comment by elmcapp** [comment]
No I did not try that. I was not sure that we had this feature. I will give
it a try. Can you provide an example of how to use the close function

**Comment by dinchak** [comment]
Sure, see this link
https://github.com/dinchak/node-easymidi#closing-devices

Try calling `.close()` on the input after you select a new option, then create a new input with the new "selectedDevice".

**Comment by dinchak** [comment]
Closing for now.  Good luck!
