### ISSUE TITLE
Sysex does not work

### ISSUE THREAD

**Issue by DPCLive** [dinchak/node-easymidi#27]
Hello,

We are using your library for one of our project.

All the commands work (faders, buttons, etc ...) But not the sysex commands:

Our commands work well with Bome SendSX.

Here's my order:

output.send ('sysex', [240,00,00,66,14,12,00,20,20,43,48,32,20,20,20,20,43,48,32,20,20,20,20,20,20,20,247]);

and in the SendSX software:  f0 00 00 66 14 12 00 20 20 43 48 32 20 20 20 20 43 48 32 20 20 20 20 20 20 20

Do you have an explanation for the problem?

Sorry, I'm french

**Comment by DPCLive** [comment]
It's okay, you had to do this, sorry:

[0xf0,0x0,0x0,0x66,0x14,0x12,0x0,0x20,0x20,0x43,0x48,0x32,0x20,0x20,0x20,0x20,0x43,0x48,0x31,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0xf7]

**Comment by dinchak** [comment]
Here are two ideas:

1) You say you send f0 in the SendSX and correctly translate it to the decimal value, 240.  But you show many other values that have not been converted to decimal.  Double check these values please and make sure they are the correct hex/decimal value.

2) You have an additional 247 in output.send and it is not present in SendSX, so they do not appear to be the same data strings.

Please double check values and let me know if you still have trouble.

**Comment by dinchak** [comment]
Oh good, yes, using the javascript hexadecimal format will probably be easier for this.  Good luck with the project!
