### ISSUE TITLE
.close() doesn't close input on Debian

### ISSUE THREAD

**Issue by MzlmDmn** [dinchak/node-easymidi#31]
Hi,
I'm using easymidi and usb-detection together to handle connect and disconnect of midi controllers.
I'm using Debian 10 and at every usb change, I clean devices by using close() function on both input and output of each device before rechecking. But as I verify my inputs, I can see that it doesn't close them, virtual "rtMidi" inputs and outputs stacks up within getInputs()/getOutputs() until ALSA throws an error because it cannot allocate memory anymore.

I'm doing it in Typescript, an interface is set with in and out as easymidi.Input and easymidi.Output type, the function close() is recognized and doesn't throw an error when called but it has no effect on the virtual ports created.

If someone has an idea of what is wrong here, I'm all hears
Thanks for reading

**Comment by dinchak** [comment]
Hello! The `close()` function in easy-midi is just a wrapper around the node-midi `closePort()` function.  I would suggest experimenting with the node-midi library directly to see if you can track down what's going on.

https://github.com/justinlatimer/node-midi

Happy to accept a pull request if you find the solution! Good luck!
