### ISSUE TITLE
Error handeling 

### ISSUE THREAD

**Issue by robinhaugan** [dinchak/node-easymidi#32]
Hey! 
I can't find any way to do error handling. 
If you create an output. Then lose connection to the midi console. how can I get an error?
I only get a console message error when trying to send a message on the disconnected output. but is not able to catch it anywhere.
Do you have a solution?

**Comment by dinchak** [comment]
This project provides a simple translation layer to parse MIDI messages but does not handle the low level MIDI communication with hardware and related error handling.  I think you will have to investigate upstream in the https://github.com/justinlatimer/node-midi project.

**Comment by robinhaugan** [comment]
Hmm, okey. Thanks!

**Comment by dinchak** [comment]
Wanted to mention that the underlying midi package has been updated to version 2.0.0, it might fix your issue! Thanks
