### ISSUE TITLE
The module "midi" is supposedly non-context-aware, despite being updated to support Electron.

### ISSUE THREAD

**Issue by Mister-SOSA** [dinchak/node-easymidi#35]
Forgive me if I'm making some sort of mistake, but I am trying to load `easymidi` into my Electron app. Upon requiring the package, I get the following error:

`Uncaught Error: Loading non-context-aware native module in renderer: '\\?\C:\Users\my_user\Documents\Midi-App\midi-electron\node_modules\midi\build\Release\midi.node'. See https://github.com/electron/electron/issues/18397.`

Upon further research, I see that `midi` _was_ in fact updated to be context aware, and your wrapper _does_ use the latest version, so what gives?

To reproduce the error, simply add `const easymidi = require('easymidi');` to your `main.js` file before running `npm start`.

**Comment by dinchak** [comment]
Hello!

Sorry, I haven't tried this in Electron yet so I'm not really sure what it
might be.  If you figure out it would you please post an update?

Thanks!!

**Comment by Mister-SOSA** [comment]
I'll try and wrestle with it and see what I can do to avoid this error. I'm not too familiar with context awareness, but I do know it involves thread management, per [this article](https://nodejs.github.io/node-addon-examples/special-topics/context-awareness/). And I do know that Electron no longer allows non-context-aware modules to be loaded into an application, per [this issue](https://github.com/electron/electron/issues/18397). `midi` already [adapted to this new standard](https://github.com/justinlatimer/node-midi/pull/214), and your wrapper was updated to support it, so I'm not sure where the disconnect is. I'll try and fiddle with it a little more.

**Comment by dinchak** [comment]
Much appreciated! If there's a pull request or patch I can apply to fix it
I'll be happy to do so.

**Comment by Mister-SOSA** [comment]
Upon further inspection, it appears that the original `midi` module was not successfully updated to support Electron's context-aware standards. It would seem that your module is fine, but fails to pass the new standards because the underlying module is essentially outdated. I'll close this issue and open one over there.
