### ISSUE TITLE
MidiInWinMM::openPort: error creating Windows MM MIDI input port. 

### ISSUE THREAD

**Issue by mrsydster** [dinchak/node-easymidi#36]
When using this lib on Windows, I keep getting the following error: 

`MidiInWinMM::openPort: error creating Windows MM MIDI input port.`

Is there something I am missing?

**Comment by dinchak** [comment]
Hello! Could you give me a bit more info on what you're working on? Source code would be helpful as well.  Thanks!

**Comment by mrsydster** [comment]
Turns out the message is just very generic. 

The midi controller was in use somewhere else, therefor could not be used.
