### ISSUE TITLE
Bad midi device name 

### ISSUE THREAD

**Issue by ArtGateOne** [dinchak/node-easymidi#37]
Old format - "midi device name #' new format 'midi device name'
My friend upgrade nodejs from 14.x to 16.x and sothig wrong happend ...
System display names with 2-

Somthing like this
'2- BCF2000'

HOW TOO RESOLVE ?

**Comment by ArtGateOne** [comment]
I have problem on my PC too

I have two novation launchpad mk3

system get input two time the same names..


Code get error



Midi IN
[
  'LPMiniMK3 MIDI',
  'MIDIIN2 (LPMiniMK3 MIDI)',
  'LPMiniMK3 MIDI',
  'MIDIIN4 (LPMiniMK3 MIDI)'
]
Midi OUT
[
  'Microsoft GS Wavetable Synth',
  'LPMiniMK3 MIDI',
  'MIDIOUT2 (LPMiniMK3 MIDI)',
  'LPMiniMK3 MIDI',
  'MIDIOUT4 (LPMiniMK3 MIDI)'
]


MidiInApi::setCallback: a callback function is already set!


MidiInWinMM::openPort: a valid connection already exists!


MidiInWinMM::openPort: error creating Windows MM MIDI input port.


MidiInApi::setCallback: a callback function is already set!





this is my code

var easymidi = require('easymidi');


//display all midi devices
console.log("Midi IN");
console.log(easymidi.getInputs());
console.log("Midi OUT");
console.log(easymidi.getOutputs());
console.log(" ");




// Monitor all MIDI inputs with a single "message" listener
easymidi.getInputs().forEach(function(inputName){
  var input = new easymidi.Input(inputName);
  input.on('message', function (msg) {
    var vals = Object.keys(msg).map(function(key){return key+": "+msg[key];});
    console.log(inputName+": "+vals.join(', '));
  });
});

**Comment by D3visionNL** [comment]
> Old format - "midi device name #' new format 'midi device name' My friend upgrade nodejs from 14.x to 16.x and sothig wrong happend ... System display names with 2-
> 
> Somthing like this '2- BCF2000'
> 
> HOW TOO RESOLVE ?

The naming issue with the "2- " has to do with how Windows handles MIDI devices. It's annoying but it doesn't have anything to do with this node module. You can fix it by using software like the [KORG USB-MIDI Driver Uninstaller](https://www.korg.com/us/support/download/driver/1/285/3856/) to uninstall all the other versions of the MIDI device that are registered in Windows.

**Comment by D3visionNL** [comment]
> I have problem on my PC too
> 
> I have two novation launchpad mk3
> 
> system get input two time the same names..
> 
> Code get error
> 
> Midi IN [ 'LPMiniMK3 MIDI', 'MIDIIN2 (LPMiniMK3 MIDI)', 'LPMiniMK3 MIDI', 'MIDIIN4 (LPMiniMK3 MIDI)' ] Midi OUT [ 'Microsoft GS Wavetable Synth', 'LPMiniMK3 MIDI', 'MIDIOUT2 (LPMiniMK3 MIDI)', 'LPMiniMK3 MIDI', 'MIDIOUT4 (LPMiniMK3 MIDI)' ]
> 
> MidiInApi::setCallback: a callback function is already set!
> 
> MidiInWinMM::openPort: a valid connection already exists!
> 
> MidiInWinMM::openPort: error creating Windows MM MIDI input port.
> 
> MidiInApi::setCallback: a callback function is already set!
> 
> this is my code
> 
> var easymidi = require('easymidi');
> 
> //display all midi devices console.log("Midi IN"); console.log(easymidi.getInputs()); console.log("Midi OUT"); console.log(easymidi.getOutputs()); console.log(" ");
> 
> // Monitor all MIDI inputs with a single "message" listener easymidi.getInputs().forEach(function(inputName){ var input = new easymidi.Input(inputName); input.on('message', function (msg) { var vals = Object.keys(msg).map(function(key){return key+": "+msg[key];}); console.log(inputName+": "+vals.join(', ')); }); });

This is another issue with Windows and not with the EasyMidi module. I don't exactly know what's causing this but I'm guessing it's a driver issue of some sort which makes it so Windows doesn't properly register multiple of the same device.

**Comment by ArtGateOne** [comment]
Ok thx

wt., 3 maj 2022, 10:31 użytkownik D3vision ***@***.***>
napisał:

**Comment by dinchak** [comment]
Thank you D3visionNL
