### ISSUE TITLE
Context awareness

### ISSUE THREAD

**Issue by D3visionNL** [dinchak/node-easymidi#38]
Hi, when trying to run this module in Electron in a window I get the error that this module is not context aware and therefore cannot run. I have done some digging and found that this is an issue with the "node-midi" module that easy-midi depends on. 

@dinchak, if you have the time and knowledge would you please be able to make a fork of the "node-midi" package and make it context aware? I have tried myself but I am simply not experienced enough and the 2 pull requests on "node-midi" did not work (plus the author of "node-midi" seems to be inactive).

I understand if you are unable to do this but regardless of that I want to thank you in advance.

Best regards,
D3vision

**Comment by sx-spider** [comment]
@D3visionNL Hi, I saw you closed this issue. Is there a way to solve this problem?
