### ISSUE TITLE
Disconnect/Reconnect events?

### ISSUE THREAD

**Issue by tiagosiebler** [dinchak/node-easymidi#39]
Firstly, thanks for making this! Having fun with an 8x8 neotrellis buttom matrix over midi. 

If I disconnect the device (after successfully connecting before), everything works perfectly once I reconnect the device.

I was hoping to send midi events to the device after it reconnects (e.g. to reset device state such as brightness, colour, etc per button). Is there a way to detect if a midi device disconnected & reconnected? 

I would imagine to emit an event for this, so an implementation like mine can use that as a trigger to re-sync all device states.

**Comment by dinchak** [comment]
What you describe sounds reasonable!

This module uses https://github.com/justinlatimer/node-midi under the hood, and is really just a simple wrapper to parse the incoming data stream/vice versa. I took a look through documentation/source code/issues for the node-midi module but I didn't really see a way to detect an unplugged/disconnect type event either, and unfortunately adding something to the node-midi module like that is a bit beyond my abilities.

However, if through experimenting with node-midi you find a way to detect a disconnect and/or reconnect type event I'd be happy to bubble those events up in easymidi.

**Comment by tiagosiebler** [comment]
That's a great point you've made there, not sure why I posted this here and not in node-midi. Coffee must've been wearing off - thanks for the quick reply (and again for this wonderful wrapper around node-midi).
