### ISSUE TITLE
midi over usb

### ISSUE THREAD

**Issue by staminna** [dinchak/node-easymidi#4]
I play notes on my midi keyboard, console.log(input.on), nothing on the screen.
I am using a novation mininova to a focusrite via usb. How do you configure such hardware?

**Comment by dinchak** [comment]
Hello,

Please see `examples/list_ports.js`.  Use this to get the names of your connected MIDI devices.  For example, you may have an input device named "Focusrite Input" or something similar.  Use the exact name reported as follows:

```javascript
let input = new easymidi.Input('Focusrite Input')`
input.on('noteon', msg => console.log(msg))
```

Connect the Mininova with a MIDI cable to the input of the Focusrite.  Hopefully you will see MIDI note on messages.

**Comment by staminna** [comment]
Thanks for quick reply. It works!
