### ISSUE TITLE
more midi devices

### ISSUE THREAD

**Issue by ArtGateOne** [dinchak/node-easymidi#44]
The code doesn't assign numbers to devices if two or more identical ones are connected, making it impossible to refer to them individually.

In previous versions, devices were numbered, but it also caused issues.

It would be nice if each identical device had a number assigned:

midi_dev
midi_dev 1 ...

![image](https://github.com/dinchak/node-easymidi/assets/65070703/ae85c3e6-7660-4ee2-9f07-91aad107d29a)

**Comment by atomic7122** [comment]
I fixed this in: https://github.com/dinchak/node-easymidi/pull/45
