### ISSUE TITLE
Handling connection state changes.

### ISSUE THREAD

**Issue by 7heMech** [dinchak/node-easymidi#47]
How can you check if connection is closed is there something like:
```js
input.on('close');
```

**Comment by dinchak** [comment]
This library is a simple wrapper around https://github.com/justinlatimer/node-midi which handles the lower level device events. Unfortunately a quick glance at the README and test scripts doesn't show an obvious way to listen for this type of message. You may need to submit a pull request to the node-midi package to make this work.
