### ISSUE TITLE
Error creating OS-X MIDI client object (rtmidi issue)

### ISSUE THREAD

**Issue by praisethemoon** [dinchak/node-easymidi#5]
Fantastic library. Simply amazing. I have the following which raises when calling 
```
easymidi.getInputs();
```

MidiInCore::initialize: error creating OS-X MIDI client object.
libc++abi.dylib: terminating with uncaught exception of type RtMidiError

Note that `getOutputs` does not cause this issue.

Setup: MacOS Mojave 
environment:
```
praisethemoon$ node --version
v10.15.1
praisethemoon$ electron --version
v4.1.3
moonpiano praisethemoon$ npm --version
6.4.1
```
AFAIK this is obviously related to the native module `rtmidi` and this issue is known and reported here: https://github.com/thestk/rtmidi/issues/155

Even though I know the issue is not from this project per se, but just to let you know.

**Comment by marksyzm** [comment]
The midi module is now updated that this communicates with to 1.0.0. I'm up for doing a pull request for this if the owner doesn't mind.

**Comment by dinchak** [comment]
merged and published as v1.0.2!

**Comment by praisethemoon** [comment]
Gonna test it ASAP and close the issue! Thank you for the good news!

**Comment by praisethemoon** [comment]
Nice work everyone! Thank you very much! I hope this app would cause less latency compared to webmidi standard on my electron app ^^ 

Cheers!
