### ISSUE TITLE
Need copyright/license information to give proper credit

### ISSUE THREAD

**Issue by praisethemoon** [dinchak/node-easymidi#8]
I have the bad habit of giving people the credit they merit, unlike many other developers. Mind specifying which license you intent to use for your library?

**Comment by dinchak** [comment]
added MIT license

**Comment by praisethemoon** [comment]
Thank you.

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/22145460/62417024-6aa57780-b63d-11e9-8f2a-4093ccee8876.png">
